version: 0.1.0
spec:
  units:
    - unit: &unitDirectory
        name: "directory"
        regex: "^/|(/[\\w-]+)+$"
        examples:
          - "/tmp/xyz"
    - unit: &unitPort
        name: "port"
        regex: "^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"
properties:
  - property: &port
      propertyNames:
        - name: "port"
          kind:
            type: "file"
            file: "zoo.cfg"
      datatype:
        type: "string"
        unit: *unitPort
      defaultValues:
        - value: "2181"
      recommendedValues:
        - value: "2181"
      roles:
        - name: "server"
          required: true
      asOfVersion: "0.0.0"
      description: "The port for the WebUi."
