= Stackable Operator for Monitoring and Metrics

This is a Kubernetes Operator to manage Monitoring and Metrics ensembles.

It is written by https://www.stackable.de[Stackable] in Rust, and it is supposed to be used with the https://github.com/stackabletech/agent[Stackable Agent] instead of the Kubernetes kubelet.

The docs can be found in the `docs` subdirectory, and they are published together with docs for all other Stackable products at https://docs.stackable.tech.

Currently, this operator uses Prometheus as a metric aggregator per machine. It may be switched out for the more lightweight VictoriaMetrics. It should be deployed on every machine/node once.

It uses Kubernetes Service Discovery to scrape pods belonging to its machine/node.
Pods that should be scraped need to expose a container port called "metrics" as well as an annotation "monitoring.stackable.tec/should_be_scraped=true".

== Building

This operator is written in Rust.
It is developed against the latest Rust release (1.53 at the time of writing this).

    cargo build

== Configuration Options

The cluster can be configured via a YAML file. This custom resource specifies the amount of replicas for each role group, role group or role specific configuration like port definition etc.

    apiVersion: monitoring.stackable.tech/v1alpha1
    kind: MonitoringCluster
    metadata:
      name: simple
    spec:
      version: 2.28.1
      servers:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/arch: stackable-linux
            replicas: 1
            config:
              webUiPort: 10101
              scrapeInterval: 15s
              scrapeTimeout: 5s
              evaluationInterval: 10s
              scheme: http

=== Structure

There are three levels of configuration:

[cols="1,1"]
|===
|Common shared options
|Contains configuration that is shared within the whole cluster ensemble. E.g. version, image, encryption or logging.

|Role options
|This configuration is shared for all roles of a certain type (in this operator, only the Server role).

|RoleGroup options
|Options provided in the role group apply to each created "pod".
|===

=== Common shared options
[cols="1,1,1,1"]
|===
|Name
|Type
|Description
|Related Prometheus/Victoria properties

|version
|string
|The Monitoring version used in the format: x.y.z
|
|===

=== Role & RoleGroup options
We summarize Role and RoleGroup options. They are the same options for Role and RoleGroup.

==== Server
[cols="1,1,1,1,1"]
|===
|Name
|Type
|Description
|Related Prometheus/Victoria properties
|Location

|webUiPort
|integer
|Start the Prometheus / Victoria UI on a different port (default 9090).
|--web.listen-address
|cli

|scrapeInterval
|string
|How frequently to scrape targets from this job (10s, 1h30m). Must be higher than the scrapeTimeout.
|scrape_interval
|prometheus.yaml

|scrapeTimeout
|string
|How long until a scrape request times out. (10s, 1h30m). Must be lower than the scrapeInterval.
|scrape_timeout
|prometheus.yaml

|evaluationInterval
|string
|How frequently to evaluate rules. (10s, 1h30m).
|evaluation_interval
|prometheus.yaml

|schema
|string
|Configures the protocol scheme used for requests.
|schema
|prometheus.yaml
|===

The docs can be found in the `docs` subdirectory, and they are published together with docs for all other Stackable products at https://docs.stackable.tech.