
consolidate-commits = true
no-dev-version = false
dev-version-ext = "nightly"
pre-release-hook = ["../release/scripts/release-pre.sh"]
pre-release-commit-message = "release"
post-release-commit-message = "start next development iteration"
disable-push = true
disable-tag = true
tag-name = "{{version}}"
disable-publish = true

