= Usage

After installation, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/monitoring-operator/crd/deploy/monitoringcluster.crd.yaml

The following example creates a monitoring cluster where a Prometheus and a Node Exporter instance are deployed on each node.

Prometheus is configured using the `podAggregator` role to scrape all Pods marked with the label `monitoring.stackable.tech/should_be_scraped` **and** that are running
on the same machine as Prometheus. Properties defined in the `podAggregator.roleGroups.default.config` section are applied to Prometheus.

The role `nodeExporter` is used to configure the Node Exporter. Metrics are exposed on port `10102` and the `nodeExporterArgs` are passed on to the `node-exporter` executable
as command line arguments.

The cluster can be configured via a YAML file. This custom resource specifies the amount of replicas for each role group, role group or role specific configuration like port definition etc. The 'podAggregator' and 'nodeExporter' have no replicas specified which means that on each available node, a pod is scheduled. The 'federation', which collects metrics from all 'podAggregator' pods and 'nodeExporter' pods can be specified to a desired amount (=1 in the example).

    apiVersion: monitoring.stackable.tech/v1alpha1
    kind: MonitoringCluster
    metadata:
      name: simple
    spec:
      version: 2.28.1
      podAggregator:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/arch: stackable-linux
            config:
              webUiPort: 10101
              scrapeInterval: 15s
              scrapeTimeout: 5s
              evaluationInterval: 10s
              scheme: http
      nodeExporter:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/arch: stackable-linux
            config:
              metricsPort: 10102
              nodeExporterArgs:
                - "--no-collector.wifi"
                - "--no-collector.hwmon"
                - "--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)"
                - "--collector.netclass.ignored-devices=^(veth.*|[a-f0-9]{15})$"
                - "--collector.netdev.device-exclude=^(veth.*|[a-f0-9]{15})$"
      federation:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/arch: stackable-linux
            replicas: 1
            config:
              webUiPort: 10103
              scrapeInterval: 15s
              scrapeTimeout: 5s
              evaluationInterval: 10s
              scheme: http

=== Structure

There are three levels of configuration:

[cols="1,1"]
|===
|Common shared options
|Contains configuration that is shared within the whole cluster ensemble. E.g. version, image, encryption or logging.

|Role options
|This configuration is shared for all roles of a certain type (in this operator, only the Server role).

|RoleGroup options
|Options provided in the role group apply to each created "pod".
|===

=== Common shared options
[cols="1,1,1,1"]
|===
|Name
|Type
|Description
|Related Prometheus/Victoria properties

|version
|string
|The Monitoring version used in the format: x.y.z
|
|===

=== Role & RoleGroup options
We summarize Role and RoleGroup options. They are the same options for Role and RoleGroup.

==== PodAggregator
[cols="1,1,1,1,1"]
|===
|Name
|Type
|Description
|Related Prometheus/Victoria properties
|Location

|webUiPort
|integer
|Start the Prometheus / Victoria UI on a different port (default 9090).
|--web.listen-address
|cli

|scrapeInterval
|string
|How frequently to scrape targets from this job (10s, 1h30m). Must be higher than the scrapeTimeout.
|scrape_interval
|prometheus.yaml

|scrapeTimeout
|string
|How long until a scrape request times out. (10s, 1h30m). Must be lower than the scrapeInterval.
|scrape_timeout
|prometheus.yaml

|evaluationInterval
|string
|How frequently to evaluate rules. (10s, 1h30m).
|evaluation_interval
|prometheus.yaml

|schema
|string
|Configures the protocol scheme used for requests.
|schema
|prometheus.yaml
|===

==== NodeExporter
[cols="1,1,1,1,1"]
|===
|Name
|Type
|Description
|Related Prometheus/Victoria properties
|Location

|metricsPort
|integer
|Start the Prometheus Node Exporter on a different port (default 9100).
|--web.listen-address
|cli

|nodeExporterArgs
|Array[string]
|Configuration parameters on what and how to scrape node metrics.
|
|cli
|===

==== Federation
[cols="1,1,1,1,1"]
|===
|Name
|Type
|Description
|Related Prometheus/Victoria properties
|Location

|webUiPort
|integer
|Start the Prometheus / Victoria UI on a different port (default 9090).
|--web.listen-address
|cli

|scrapeInterval
|string
|How frequently to scrape targets from this job (10s, 1h30m). Must be higher than the scrapeTimeout.
|scrape_interval
|prometheus.yaml

|scrapeTimeout
|string
|How long until a scrape request times out. (10s, 1h30m). Must be lower than the scrapeInterval.
|scrape_timeout
|prometheus.yaml

|evaluationInterval
|string
|How frequently to evaluate rules. (10s, 1h30m).
|evaluation_interval
|prometheus.yaml

|schema
|string
|Configures the protocol scheme used for requests.
|schema
|prometheus.yaml
|===

