= Usage

After installation, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/monitoring-operator/crd/monitoringcluster.crd.yaml

To create a single node Apache ZooKeeper (v3.5.8) cluster with Prometheus metrics exposed on port 9505:


    cat <<EOF | kubectl apply -f -
    apiVersion: monitoring.stackable.tech/v1alpha1
    kind: MonitoringCluster
    metadata:
      name: simple
    spec:
      version: 2.28.1
      nodePods:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/arch: stackable-linux
            config:
              webUiPort: 10101
              scrapeInterval: 15s
              scrapeTimeout: 5s
              evaluationInterval: 10s
              scheme: http
      node:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/arch: stackable-linux
            config:
              metricsPort: 10102
              nodeExporterArgs:
                - "--no-collector.wifi"
                - "--no-collector.hwmon"
                - "--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)"
                - "--collector.netclass.ignored-devices=^(veth.*|[a-f0-9]{15})$"
                - "--collector.netdev.device-exclude=^(veth.*|[a-f0-9]{15})$"
      EOF

