= Usage

After installation, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/monitoring-operator/crd/monitoringcluster.crd.yaml

The following example creates a monitoring cluster where a Prometheus and a Node Exporter instance is deployed on each node.

Prometheus is configured using the `nodePods` role to scrape all Pods marked with the label `monitoring.stackable.tech/should_be_scraped` **and** that are running
on the same machine as Prometheus. Properties defined in the `nodePods.roleGroups.default.config` section are applyed to Prometheus.

The role `node` is used to configure the Node Exporter. Metrics are exposed on port `10102` and the `nodeExporterArgs` are passed on to the `node-exporter` executable
as command line arguments.

    cat <<EOF | kubectl apply -f -
    apiVersion: monitoring.stackable.tech/v1alpha1
    kind: MonitoringCluster
    metadata:
      name: simple
    spec:
      version: 2.28.1
      nodePods:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/arch: stackable-linux
            config:
              webUiPort: 10101
              scrapeInterval: 15s
              scrapeTimeout: 5s
              evaluationInterval: 10s
              scheme: http
      node:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/arch: stackable-linux
            config:
              metricsPort: 10102
              nodeExporterArgs:
                - "--no-collector.wifi"
                - "--no-collector.hwmon"
                - "--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)"
                - "--collector.netclass.ignored-devices=^(veth.*|[a-f0-9]{15})$"
                - "--collector.netdev.device-exclude=^(veth.*|[a-f0-9]{15})$"
      EOF

