apiVersion: monitoring.stackable.tech/v1alpha1
kind: MonitoringCluster
metadata:
  name: simple
spec:
  version: 2.28.1
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        replicas: 1




